#!/bin/bash
# Reads .env and writes Sources/ClaudeQuota/Auth/GeneratedCredentials.swift from it. Both the
# input and the output are gitignored — this script is the only thing that should ever produce
# that Swift file. Run manually, or via build_app.sh which calls this first.
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$DIR"

ENV_FILE=".env"
OUT_FILE="Sources/ClaudeQuota/Auth/GeneratedCredentials.swift"

if [ ! -f "$ENV_FILE" ]; then
    echo "Missing $ENV_FILE." >&2
    echo "Copy .env.example to .env and fill in the ANTIGRAVITY_* values (or run" >&2
    echo "scripts/fetch_secrets.sh to fetch what can be fetched automatically) — see" >&2
    echo "doc/features/oauth-credentials.md." >&2
    exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

: "${CLAUDE_CLIENT_ID:?Missing CLAUDE_CLIENT_ID in .env}"
: "${CODEX_CLIENT_ID:?Missing CODEX_CLIENT_ID in .env}"
: "${ANTIGRAVITY_CLIENT_ID:?Missing ANTIGRAVITY_CLIENT_ID in .env}"
: "${ANTIGRAVITY_CLIENT_SECRET:?Missing ANTIGRAVITY_CLIENT_SECRET in .env}"

for placeholder in "$ANTIGRAVITY_CLIENT_ID" "$ANTIGRAVITY_CLIENT_SECRET"; do
    if [ "$placeholder" = "REPLACE_ME" ]; then
        echo "ANTIGRAVITY_CLIENT_ID/SECRET in .env is still the placeholder REPLACE_ME." >&2
        echo "Run scripts/fetch_secrets.sh, or fill it in by hand — see" >&2
        echo "doc/features/oauth-credentials.md." >&2
        exit 1
    fi
done

mkdir -p "$(dirname "$OUT_FILE")"
cat > "$OUT_FILE" << SWIFT
// GENERATED by scripts/generate_credentials.sh from .env — do not edit by hand, do not commit
// (both this file and .env are gitignored). Re-run the script after changing .env.
enum GeneratedCredentials {
    static let claudeClientID = "$CLAUDE_CLIENT_ID"
    static let codexClientID = "$CODEX_CLIENT_ID"
    static let antigravityClientID = "$ANTIGRAVITY_CLIENT_ID"
    static let antigravityClientSecret = "$ANTIGRAVITY_CLIENT_SECRET"
}
SWIFT

echo "Generated $OUT_FILE from $ENV_FILE"
